{% set name = "amzn-sagemaker-aiops-jupyterlab-extension" %}
{% set version = "1.0.3" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/amzn_sagemaker_aiops_jupyterlab_extension-{{ version }}.tar.gz
  sha256: f515f979f9782d5ea5ec22128cce37045900d7b98beaf03e095d404c911120ab

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.5.0
    - jupyterlab >=4.0,<5.dev0
    - hatch-nodejs-version >=0.3.2
    - hatch-jupyter-builder
    - pip
  run:
    - python >={{ python_min }}
    - jupyterlab >=4
    - jupyter_events >=0.6.0
    - async-lru
    - aws-embedded-metrics
    - aiobotocore >=2.7.0
    - y-py >=0.6.0,<0.7.0
    - ypy-websocket >=0.12.0
    - nbformat >=5.9.2
    - pydantic >=1.10.17,<3

test:
  imports:
    - amzn_sagemaker_aiops_jupyterlab_extension
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://aws.amazon.com/sagemaker
  summary: SageMaker AI Ops JupyterLab workspace primary extension module
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ratikkoka
    - rkoka-amzn
